spring.application.name=MS-Payments

#KAFKA CONFIGURATION
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=instant-payment-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# ==== Database Configuration ====
spring.datasource.url=jdbc:sqlserver://AVAPC-141153941\\SQLEXPRESS:1433;databaseName=MS-Payments;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=admin
spring.datasource.password=yourStrong(!)Password
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ==== Server HTTPS do PAYMENT-SERVICE ====
server.ssl.key-store=classpath:Certifications/keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot

# ==== TRUSTSTORE (para confiar no WALLET-SERVICE) ====
server.ssl.trust-store=classpath:Certifications/truststore.jks
server.ssl.trust-store-password=changeit
server.ssl.trust-store-type=JKS
